# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /pretty/

# Setup
title:            Jay Menor
tagline:          'A Jekyll theme'
description:      'I build stuff for the web.'
url:              https://hmenorjr.github.io
baseurl:          /

author:
  name:           'Jay Menor'
  url:            https://twitter.com/hmenorjr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hmenorjr/hmenorjr.github.io
