# Dependencies
markdown:     redcarpet
highlighter:  pygments

# Setup
title: "Jay Menor"
email: herman.menor@gmail.com
description:
  I'm a Computer Science almunus, web developer, software engineer and automator.
  I help businesses through coding.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hmenorjr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hmenorjr
github_username:  hmenorjr

# Build settings
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed
  - jekyll-seo-tag